### ISSUE TITLE
An error occurred when sending the request

### ISSUE THREAD

**Issue by mal68** [walterpg/google-drive-sync#13]
When any of my databases attempt to upload to Google drive it fails, with the following error ' An error occurred when sending the request'.

I have only just upgraded to this from Google sync and have been struggling to get it working. I have tried custom OAuth 2.0 credentials but that doesn't seem to have helped. I am by no means an expert on this so if this not a bug but merely me not knowing what I am doing I apologise and would just appreciate some help.

Cheers

**Comment by walterpg** [comment]
I'm sorry you are having problems, I hope we can get you working again.

The error must be in the browser because the plugin doesn't have an error message with that exact verbiage. Google will show intimidating error messages when you use the old plugin's default credentials and even if you use your own custom creds.  Unfortunately custom creds is an increasingly difficult path, but last I checked was still a usable alternative.  

To get further assistance you will need to provide further details, including screenshots.  

Hopefully, very soon, we will have a general, more realistic solution, so don't give up hope!

**Comment by walterpg** [comment]
I hope you were able to find a solution.

If not, please check out the [latest release](https://github.com/walterpg/google-drive-sync/releases/tag/v4.0.2-beta), and be sure to read the Release Notes, especially the "UPGRADE" instructions to remove the previous release.
