### ISSUE TITLE
the authenticated client is not autorizied

### ISSUE THREAD

**Issue by badplay** [walterpg/google-drive-sync#25]
Hi i get after some days of work

the authenticated client is not autorizied to use this authorization grant type

what should i do?

**Comment by walterpg** [comment]
Hi, sorry for the slow response.  Perhaps the plugin's app credential was revoked.  This can only happen if you or Google explicitly do so.  If they have not given you any kind of warning or other indication that they have revoked the plugin's credentials, you may have unintentionally initiated this, either via one of Google's "security checkup" wizards, or by removing authorization for an app you didn't recognize.  

The strange thing here is that the plugin should recognize this condition, and simply prompt you to authorize again.

For the record, the plugin's app credential name is
### KeePass Sync for Google Drive
as opposed to the legacy plugin (v3) app credential name, which was:
### KeePass GoogleSyncPlugin
You can view which applications currently have some form of access to your drive account in Drive's settings:

![Drive Apps](https://user-images.githubusercontent.com/15221668/103180523-dbb18480-485b-11eb-919b-342ae1447612.png)

Are you using your own app credentials instead of the "built-in" credentials shown above?  It is highly recommended to use the *new* built-in credentials, rather than v3 or "personal" app credentials, for the best, most consistent behavior.  The other credential types are fully deprecated and Google's compatibility with them cannot be assured.  The plugin will still allow you to use them, but I expect Google's tolerance of them will diminish going forward.

You might try deleting the refresh token data from the plugin entry.  In KeePass, open the password entry used to configure the plugin, and click on the Properties tab, as shown:

![Refresh token](https://user-images.githubusercontent.com/15221668/103180867-84adae80-485f-11eb-92ff-d9f837bd4884.png)

If this "Plugin data" entry is not present, the plugin cannot use your prior authorization to authenticate, and will be forced to prompt you for permission to use Drive again.

**Comment by walterpg** [comment]
Closing this issue for lack of further feedback...reopen if needed.
