### ISSUE TITLE
OAuth flow is currently broken when using a custom Client ID and Client Secret in combination with Limited Drive Access

### ISSUE THREAD

**Issue by whalehub** [walterpg/google-drive-sync#3]
If you enter a custom Client ID and Client Secret in this plugin's configuration menu, tick the box for Limited Drive Access and try to upload a database to Google Drive, KeePass opens a new browser with the custom application's OAuth URL as expected. The problem is that the OAuth URL is invalid because the `scope` parameter in the API request is blank.

**Screenshot**
![vivaldi_2020-05-30_11-18-59](https://user-images.githubusercontent.com/44198148/83324692-5f27da80-a267-11ea-8a54-5b9fe7c8a636.png)

**Example URL**
```
https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&login_hint=<GMAIL_ADDRESS>&response_type=code&client_id=<CLIENT_ID>-<CLIENT_SECRET>&redirect_uri=http://localhost:16812/&scope=&state=<STATE>
```

**Solution**
The scopes required by the Limited Drive Access feature are `https://www.googleapis.com/auth/drive.appdata` and `https://www.googleapis.com/auth/drive.file`. Please note that the Google API requires multiple values to be separated by a single space, like this:

```
https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&login_hint=<GMAIL_ADDRESS>&response_type=code&client_id=<CLIENT_ID>-<CLIENT_SECRET>&redirect_uri=http://localhost:16812/&scope=https://www.googleapis.com/auth/drive.appdata https://www.googleapis.com/auth/drive.file&state=<STATE>
```

**#OffTopic**
Thank you, by the way, for reviving this wonderful plugin! I've been using the original SourceForce version since 2017 and have been dreading the day Google makes an API change that renders it non-functional. That hasn't happened yet, but knowing that there is an actively maintained fork puts my mind at ease.

I switched over to your version earlier today and apart from the little hiccup that this bug is about (which was easily resolvable by making those changes to the OAuth URL manually), I quite like the improvements you've made to it so far. I also recently created a fork of an abandoned KeePass plugin, if you're interested: https://github.com/whalehub/CustomGlobalHotkeys

**Comment by rootless4real** [comment]
Thank you so much for updating this plugin!  I can confirm the need for the passing of the "scope" parameter. That said, thank you for:

1) making the URL available in the browser so I could try different browser just copy/pasting the URL string and 
2) the custom OAuth works fine as long as the scope/access isn't limited.  

(I couldn't get the default OAuth to work, but that is a different issue).  Thank you again!!

**Comment by walterpg** [comment]
Thanks for the bug report, and the encouragements.  

This is a sync problem that is ultimately a more general config management issue.  You may be able to work around it by tweaking the dialog (e.g., toggle the check box off, click OK, then go back in and toggle it on).  Sorry about that. It will be fixed as soon as I can get on it.

---
**Default OAuth**

The v2.x "built-in" ClientID is basically retired by Google for new authorizations in the "unlimited" case.  If you have an old but valid refresh token stored in the KP database, they will still honor it for plugin ops (at least they do for me, for *now*).  Otherwise, with the built-in ClientID, they only reauthorize the limited access scope, and not unlimited.  If unlimited is used without a good refresh token, you'll probably get this.

![Capture](https://user-images.githubusercontent.com/15221668/83577543-19367500-a4fa-11ea-94f3-a4b5a857ec67.PNG)

Eventually, the plugin will be verified and the retired ClientID will be replaced.  Until then I advise using your own ClientID or using limited mode.

---

But unfortunately, with the present bug, the latter option may be [catch-22](https://en.wikipedia.org/wiki/Catch-22_(logic)).

**Comment by walterpg** [comment]
The scope issue should be fixed in the new release just posted.
