### ISSUE TITLE
4.0.5 and older: Updatecheck fails - Signature issue?

### ISSUE THREAD

**Issue by Rookiestyle** [walterpg/google-drive-sync#34]
Since the **release** of 4.0.6, KeePass' update check cannot parse the version information file while the plugin update has not yet been done.

Update Check showed "Update check failed. Version infomration file could not be downloaded." while still using 4.0.5
Update check shows "Up to date" after the upgrade

There seems to be an issue when verifying the signature.
I assume this is related to the name change, as this issue disappears after I upgraded from 4.0.5 to 4.0.6

**Comment by walterpg** [comment]
The [former public sig](https://github.com/walterpg/google-drive-sync/blob/master/kpsync_version_4.txt) was purposely munged, like after the prior name change.

I have no experience with such things, but I understand there are plugins that manage plugins based on the KP update check.  Which is better, "new version available" or a "failure" status?  Either way the only remedy is uninstalling - this is not a drag & drop upgrade due to the renaming.  

Since there is no "KeePass Sync for Google Drive"v4.0.6, should the update check appear to claim there is one?  Or is showing something silly like new version v19.9.9.9 a better idea?  I really don't know the right answer here.

**Comment by Rookiestyle** [comment]
At the end this boils down to the question: Is KPSync for Google Drive a new plugin or a new version and one of the changes is a renaming?

"Update check failed" for me always indicates a technical issue like missing internet connection, version info file not available, ...
My personal opinion: Showing it as "new version available" is better as users are aware that there is ** *a* ** change and the should update to 4.0.6, 4.07, ... and hopefully many more versions - this is not impacted by their usage/non-usage of other update-check-related plugins.

"Better" in this context of course depends on one's view, there is no 100% clear way to answer this question.
