### ISSUE TITLE
Error when using ID and Password to sync

### ISSUE THREAD

**Issue by Sharad0714** [walterpg/google-drive-sync#7]
I am using limited drive access since built-in OAuth credential is not working.
But when trying to use it by inputting id and password this error shows.

Authorization Error
Error 401: invalid_client
Client missing a project id.

**Comment by walterpg** [comment]
Hi, I think you may have found a bug, although I can't reproduce exactly what you are seeing.  If you successfully sync'ed with the built-in creds in limited mode, then the the Refresh Token being sent to Google after you changed to your personal OAuth creds may be stale due to a bug.  Otherwise there may be a problem with your OAuth creds.

Can you try opening the password entry for the plugin and delete this entry on the Properties page, then try again:
![issue](https://user-images.githubusercontent.com/15221668/84580992-2842e000-ada2-11ea-8ea1-dc6677b003c2.PNG)

**Comment by Sharad0714** [comment]
So forgot to let you know but I fixed it. I don't know if it's the right way to do it but it works for now.

I noticed that the plugin created a new entry in my password database so I just filled in that entry with my username and password and used built-in OAuth client and it works now.
![Annotation 2020-06-13 204258](https://user-images.githubusercontent.com/66860619/84582173-b88b2000-adb6-11ea-89cc-deb11dc2e753.png)
![Annotation 2020-06-13 204440](https://user-images.githubusercontent.com/66860619/84582190-f6884400-adb6-11ea-9fa2-96b6375d4599.png)
![Annotation 2020-06-13 204613](https://user-images.githubusercontent.com/66860619/84582203-2df6f080-adb7-11ea-9ae1-feeb2a374fd1.png)
